'use client';

import { useActionState, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { Button, Card, Field, Input, Notice, Textarea } from '@mi/ui';
import { CopyButton, FormErrors, SubmitButton } from '@mi/ui/client';
import { postPastedAgentReply, requestClaudeObservations } from '@/app/actions/agents';

type ClaudeState =
  | { kind: 'idle' }
  | { kind: 'pending' }
  | { kind: 'ok'; mock: boolean }
  | { kind: 'error'; error: string };

export function AgentsPanel({
  threadId,
  briefing,
  claudeConfigured,
}: {
  threadId: string;
  briefing: string;
  claudeConfigured: boolean;
}) {
  const router = useRouter();
  const [claudeState, setClaudeState] = useState<ClaudeState>({ kind: 'idle' });
  const [pending, startTransition] = useTransition();

  function askClaude() {
    setClaudeState({ kind: 'pending' });
    startTransition(async () => {
      const result = await requestClaudeObservations(threadId);
      if (!result.configured) {
        setClaudeState({ kind: 'error', error: 'not-configured' });
        return;
      }
      if (result.ok) {
        setClaudeState({ kind: 'ok', mock: result.mock });
        router.refresh();
      } else {
        setClaudeState({ kind: 'error', error: result.error });
      }
    });
  }

  return (
    <Card title="Agents">
      <div className="space-y-6">
        <section>
          <h3 className="text-h3 font-semibold text-fg">Ask Claude for observations</h3>
          {!claudeConfigured ? (
            <div className="mt-2">
              <Notice tone="neutral" data-testid="claude-not-configured">
                Claude observations are not configured on this server. Set ANTHROPIC_API_KEY to enable them.
              </Notice>
            </div>
          ) : (
            <p className="mt-1 text-small text-fg-secondary">
              Claude reads this thread and the data catalogue, then posts structured observations labelled
              &ldquo;Generated by Claude&rdquo;.
            </p>
          )}
          <div className="mt-3">
            <Button
              type="button"
              data-testid="claude-button"
              disabled={!claudeConfigured || pending}
              onClick={askClaude}
            >
              {pending ? 'Asking Claude…' : 'Ask Claude for observations'}
            </Button>
          </div>
          {claudeState.kind === 'error' && claudeState.error !== 'not-configured' && (
            <div className="mt-2">
              <Notice tone="danger" data-testid="claude-error">
                {claudeState.error}
              </Notice>
            </div>
          )}
          {claudeState.kind === 'ok' && (
            <div className="mt-2">
              <Notice tone="success">
                Claude posted a reply{claudeState.mock ? ' (mock)' : ''} below.
              </Notice>
            </div>
          )}
        </section>

        <section>
          <h3 className="text-h3 font-semibold text-fg">Briefing for another agent</h3>
          <p className="mt-1 text-small text-fg-secondary">
            Copy this into any other agent (ChatGPT, Gemini, a local model) and paste its answer back below.
          </p>
          <textarea
            data-testid="agent-briefing"
            readOnly
            value={briefing}
            rows={8}
            className="num mt-2 w-full rounded-md border border-border-strong bg-surface-sunken px-3 py-2.5 text-small leading-6 text-fg"
          />
          <div className="mt-2">
            <CopyButton text={briefing} label="Copy briefing" />
          </div>
        </section>

        <PasteAgentReplyForm threadId={threadId} />
      </div>
    </Card>
  );
}

function PasteAgentReplyForm({ threadId }: { threadId: string }) {
  const action = postPastedAgentReply.bind(null, threadId);
  const [state, formAction] = useActionState(action, null);
  const fieldErrors = state && !state.ok ? state.fieldErrors : undefined;

  const [agentName, setAgentName] = useState('');
  const [observations, setObservations] = useState('');
  const [suggestions, setSuggestions] = useState('');
  const [biggestRisk, setBiggestRisk] = useState('');
  const [missingInformation, setMissingInformation] = useState('');
  const [jsonText, setJsonText] = useState('');
  const [jsonError, setJsonError] = useState<string | null>(null);

  function fillFromJson() {
    try {
      const parsed = JSON.parse(jsonText) as {
        observations?: string[];
        suggestions?: Array<{ suggestion: string; reason: string }>;
        biggestRisk?: string;
        missingInformation?: string[];
      };
      setObservations((parsed.observations ?? []).join('\n'));
      setSuggestions((parsed.suggestions ?? []).map((s) => `${s.suggestion} | ${s.reason}`).join('\n'));
      setBiggestRisk(parsed.biggestRisk ?? '');
      setMissingInformation((parsed.missingInformation ?? []).join('\n'));
      setJsonError(null);
    } catch {
      setJsonError('That is not valid JSON.');
    }
  }

  return (
    <section>
      <h3 className="text-h3 font-semibold text-fg">Paste an agent&apos;s reply</h3>
      <p className="mt-1 text-small text-fg-secondary">
        Answer in the JSON shape from the briefing, or fill the fields by hand.
      </p>

      <div className="mt-3 rounded-md border border-border bg-surface-sunken p-3">
        <label htmlFor="fill-from-json" className="text-small font-medium text-fg">
          Fill from JSON
        </label>
        <textarea
          id="fill-from-json"
          value={jsonText}
          onChange={(e) => setJsonText(e.target.value)}
          rows={4}
          className="num mt-1.5 w-full rounded-md border border-border-strong bg-surface px-3 py-2 text-small"
        />
        <div className="mt-2 flex items-center gap-2">
          <Button type="button" variant="secondary" size="sm" onClick={fillFromJson}>
            Fill fields
          </Button>
          {jsonError && <span className="text-small text-negative">{jsonError}</span>}
        </div>
      </div>

      <form action={formAction} noValidate className="mt-4 space-y-4">
        <FormErrors state={state} />
        <Field label="Agent name" name="agentName" required error={fieldErrors?.agentName}>
          <Input required value={agentName} onChange={(e) => setAgentName(e.target.value)} />
        </Field>
        <Field label="Observations" name="observations" hint="One per line." error={fieldErrors?.observations}>
          <Textarea rows={4} value={observations} onChange={(e) => setObservations(e.target.value)} />
        </Field>
        <Field
          label="Suggestions"
          name="suggestions"
          hint="One per line, formatted: suggestion | reason"
          error={fieldErrors?.suggestions}
        >
          <Textarea rows={4} value={suggestions} onChange={(e) => setSuggestions(e.target.value)} />
        </Field>
        <Field label="Biggest risk" name="biggestRisk" required error={fieldErrors?.biggestRisk}>
          <Textarea rows={2} value={biggestRisk} onChange={(e) => setBiggestRisk(e.target.value)} />
        </Field>
        <Field
          label="Missing information"
          name="missingInformation"
          hint="One per line."
          error={fieldErrors?.missingInformation}
        >
          <Textarea rows={3} value={missingInformation} onChange={(e) => setMissingInformation(e.target.value)} />
        </Field>
        <SubmitButton>Post pasted reply</SubmitButton>
      </form>
    </section>
  );
}
