import type { ReactNode } from 'react';
import type { AgentReplyPayload } from '../types';
import { Badge } from './badge';
import { formatDate } from '../format';

export type AgentReplySource = 'claude_button' | 'pasted' | 'api';

export interface AgentReplyCardProps {
  payload: AgentReplyPayload;
  agentName: string;
  source: AgentReplySource;
  isMock: boolean;
  hidden: boolean;
  createdAt: Date;
  actions?: ReactNode;
}

const sourceLabel: Record<AgentReplySource, string> = {
  claude_button: 'Generated by Claude',
  pasted: 'Pasted from agent',
  api: 'Posted via API',
};

export function AgentReplyCard({ payload, agentName, source, isMock, hidden, createdAt, actions }: AgentReplyCardProps) {
  const sourceText = source === 'pasted' ? `Pasted from ${agentName}` : sourceLabel[source];
  return (
    <div
      data-testid="agent-reply"
      data-source={source}
      data-mock={isMock}
      className="rounded-lg border border-border border-l-2 border-l-accent bg-surface p-4 md:p-6"
    >
      <div className="mb-3 flex flex-wrap items-center gap-2">
        <Badge variant="agent" />
        <span className="num text-small text-fg">{agentName}</span>
        <Badge variant="generated">{sourceText}</Badge>
        {isMock && <Badge variant="mock">Mock</Badge>}
        {hidden && <Badge variant="hidden" />}
        <time dateTime={createdAt.toISOString()} className="ml-auto num text-small tnum text-fg-muted">
          {formatDate(createdAt)}
        </time>
      </div>

      <section className="space-y-4">
        <div>
          <h4 className="text-small font-semibold text-fg-secondary">Observations</h4>
          <ul className="mt-1.5 list-disc space-y-1 pl-5 text-body text-fg">
            {payload.observations.map((obs, i) => (
              <li key={i}>{obs}</li>
            ))}
          </ul>
        </div>

        {payload.suggestions.length > 0 && (
          <div>
            <h4 className="text-small font-semibold text-fg-secondary">Suggestions</h4>
            <ul className="mt-1.5 space-y-2 pl-5 text-body text-fg">
              {payload.suggestions.map((s, i) => (
                <li key={i} className="list-disc">
                  <span>{s.suggestion}</span>
                  <span className="block text-small text-fg-muted">{s.reason}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        <div>
          <h4 className="text-small font-semibold text-fg-secondary">Biggest risk</h4>
          <div className="mt-1.5 flex items-start gap-2 rounded-md bg-warning-subtle p-3 text-body text-fg">
            <svg aria-hidden="true" viewBox="0 0 16 16" className="mt-0.5 size-4 shrink-0 text-warning">
              <path d="M8 1.5 15 14.5H1Z" stroke="currentColor" strokeWidth="1.3" fill="none" strokeLinejoin="round" />
              <path d="M8 6.5v3.5M8 12v.01" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" />
            </svg>
            <span>{payload.biggestRisk}</span>
          </div>
        </div>

        {payload.missingInformation.length > 0 && (
          <div>
            <h4 className="text-small font-semibold text-fg-secondary">Missing information</h4>
            <ul className="mt-1.5 list-disc space-y-1 pl-5 text-body text-fg">
              {payload.missingInformation.map((m, i) => (
                <li key={i}>{m}</li>
              ))}
            </ul>
          </div>
        )}
      </section>

      {actions && <div className="mt-4 flex gap-2 border-t border-border pt-4">{actions}</div>}
    </div>
  );
}
