import type { ReactNode } from 'react';
import { cn } from '../format';

export type BadgeVariant =
  | 'example'
  | 'agent'
  | 'generated'
  | 'mock'
  | 'pasted'
  | 'api'
  | 'owner'
  | 'hidden'
  | 'private'
  | 'public'
  | 'tag'
  | 'neutral';

const base = 'inline-flex items-center gap-1 rounded-sm px-1.5 py-px text-micro font-medium';

const variantClasses: Record<BadgeVariant, string> = {
  example: 'border border-dashed border-warning/60 bg-warning-subtle text-warning',
  agent: 'bg-accent-subtle text-accent ring-1 ring-inset ring-accent/30',
  generated: 'bg-surface-sunken text-fg-secondary ring-1 ring-inset ring-border-strong/40',
  mock: 'bg-surface-sunken text-fg-secondary ring-1 ring-inset ring-border-strong/40',
  pasted: 'bg-surface-sunken text-fg-secondary ring-1 ring-inset ring-border-strong/40',
  api: 'bg-surface-sunken text-fg-secondary ring-1 ring-inset ring-border-strong/40',
  owner: 'bg-accent-subtle text-accent ring-1 ring-inset ring-accent/30',
  hidden: 'bg-negative-subtle text-negative',
  private: 'bg-surface-sunken text-fg-secondary',
  public: 'bg-positive-subtle text-positive',
  tag: 'bg-surface-sunken text-fg-secondary',
  neutral: 'bg-surface-sunken text-fg-secondary',
};

const defaultLabel: Partial<Record<BadgeVariant, string>> = {
  example: 'Example',
  agent: 'Agent',
  generated: 'Generated by Claude',
  hidden: 'Hidden',
};

export interface BadgeProps {
  variant: BadgeVariant;
  children?: ReactNode;
  className?: string;
  title?: string;
}

export function Badge({ variant, children, className, title }: BadgeProps) {
  const content = children ?? defaultLabel[variant] ?? variant;
  return (
    <span
      className={cn(base, variantClasses[variant], className)}
      title={variant === 'example' ? (title ?? 'Placeholder value, not a real measurement') : title}
      data-variant={variant}
      data-testid={variant === 'example' ? 'example-badge' : undefined}
    >
      {content}
    </span>
  );
}
