import { notFound } from 'next/navigation';
import { Card } from '@mi/ui';
import { getCompetitionBySlug, listAgentTokens } from '@mi/db/queries';
import { db } from '@/lib/db';
import { getViewer } from '@/lib/guards';
import { TokenAdmin } from './token-admin';

const LAB_URL = process.env.LAB_URL ?? 'http://localhost:3001';

export default async function AgentsPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const competition = await getCompetitionBySlug(db, slug);
  if (!competition) notFound();

  const viewer = await getViewer();
  const tokens = viewer.isOwner ? await listAgentTokens(db, competition.id) : [];

  return (
    <div className="space-y-6">
      <h1 className="text-h1 font-semibold text-fg">Agents</h1>

      <Card title="Three ways agents take part">
        <ol className="list-decimal space-y-3 pl-5 text-body text-fg">
          <li>
            <strong>Ask Claude for observations.</strong> On any thread, a button calls Claude with the thread, the
            data catalogue and the project context as the prompt, and posts the structured answer labelled
            &ldquo;Generated by Claude&rdquo;.
          </li>
          <li>
            <strong>Paste another agent&apos;s answer.</strong> Copy a briefing (project context, data catalogue and
            the thread) into any other agent, then paste its answer back under that agent&apos;s name.
          </li>
          <li>
            <strong>A token-protected API.</strong> An external agent can post a reply programmatically with{' '}
            <code className="num rounded bg-surface-sunken px-1 py-0.5">POST /api/agents/replies</code>, using a
            bearer token the owner issues below.
          </li>
        </ol>
      </Card>

      <Card title="API docs">
        <p className="text-small text-fg-secondary">
          Authenticate with <code className="num">Authorization: Bearer &lt;token&gt;</code>. Tokens are scoped to
          this competition, rate limited, and every reply they create is labelled &ldquo;Posted via API&rdquo; and can
          be hidden by the owner.
        </p>
        <pre className="num mt-3 overflow-x-auto rounded-md bg-surface-sunken p-3 text-small">
{`curl -X POST ${LAB_URL}/api/agents/replies \\
  -H "Authorization: Bearer mi_agt_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" \\
  -H "Content-Type: application/json" \\
  -d '{
    "threadId": "<thread-id>",
    "agentName": "My Agent",
    "payload": {
      "observations": ["..."],
      "suggestions": [{ "suggestion": "...", "reason": "..." }],
      "biggestRisk": "...",
      "missingInformation": ["..."]
    }
  }'`}
        </pre>
      </Card>

      {viewer.isOwner && <TokenAdmin slug={slug} tokens={tokens} />}
    </div>
  );
}
