import { collectionRate, margin, netMinor, totalExpensesMinor } from './ledger';
import type { LedgerMonthRow } from './public-ledger';

export const LEDGER_CSV_HEADER = [
  'month',
  'revenue',
  'paying_customers',
  'invoices_raised',
  'invoices_paid',
  'hosting',
  'speech',
  'ai_usage',
  'other',
  'total_expenses',
  'net',
  'margin',
  'collection_rate',
  'shared_publicly',
  'note',
] as const;

/** RFC 4180 quoting plus a CSV-injection guard for formula-leading text cells. */
export function csvCell(value: string | number | boolean | null | undefined, opts: { guard?: boolean } = {}): string {
  let s = value === null || value === undefined ? '' : String(value);
  if ((opts.guard ?? true) && /^[=+\-@\t\r]/.test(s)) s = `'${s}`;
  if (/[",\r\n]/.test(s)) s = `"${s.replace(/"/g, '""')}"`;
  return s;
}

const money = (minor: number) => (minor / 100).toFixed(2);
const ratio = (r: number | null) => (r === null ? '' : r.toFixed(4));

/** Money in major units with 2 dp; ratios with 4 dp (empty when undefined). Rows sorted by month. */
/** `_currency` is accepted for the contract; amounts are plain numbers in that currency. */
export function ledgerToCsv(rows: LedgerMonthRow[], _currency: string): string {
  const lines = [LEDGER_CSV_HEADER.join(',')];
  const sorted = [...rows].sort((a, b) => (a.month < b.month ? -1 : a.month > b.month ? 1 : 0));
  for (const r of sorted) {
    // Numeric cells are generated by us (negative net starts with '-'), so the guard only applies to text.
    lines.push(
      [
        csvCell(r.month.slice(0, 7)),
        csvCell(money(r.revenueMinor), { guard: false }),
        csvCell(r.payingCustomers, { guard: false }),
        csvCell(r.invoicesRaised, { guard: false }),
        csvCell(r.invoicesPaid, { guard: false }),
        csvCell(money(r.hostingMinor), { guard: false }),
        csvCell(money(r.speechMinor), { guard: false }),
        csvCell(money(r.aiUsageMinor), { guard: false }),
        csvCell(money(r.otherMinor), { guard: false }),
        csvCell(money(totalExpensesMinor(r)), { guard: false }),
        csvCell(money(netMinor(r)), { guard: false }),
        csvCell(ratio(margin(r)), { guard: false }),
        csvCell(ratio(collectionRate(r)), { guard: false }),
        csvCell(r.sharedPublicly ? 'true' : 'false'),
        csvCell(r.note),
      ].join(','),
    );
  }
  return lines.join('\r\n') + '\r\n';
}
